### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by rurirei** [rurirei/Kitsunebi#4]
### DEVELOPMENT
 - [ ] service in separate process
 - [ ] fix for known issues

### FEATURE
 - [x] ipv6 support #11 
 - [ ] latency and availbility test
 - [ ] speed stats in notification
 - [ ] traffic stats in notification
 - [ ] start connection with system booting
 - [ ] subscription (Pull Request welcome) #10 
 - [ ] qrcode scanner (Pull Request welcome)

//////////////////////////////////////////////////////////////////

### DEVELOPMENT
 - UI for create v2ray configuration. **custom config support only always**
 - translation

### FEATURE
 - pre-provided rule
 - dynamic endpoint
 - fail over, load balance
 - dns custom configuration 2dust/v2rayNG#653

**Comment by rurirei** [comment]
New Plan: create a branch for Clash open-source branch next year.

**Comment by rurirei** [comment]
Now: UI Help Wanted!
